cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
	path('remove/<int:id>', views.cart_remove, name='cart_remove'),
	path('add/<int:id>', views.cart_add, name='cart_add'),
	path('', views.cart_detail, name='cart_detail')
]

order/urls.py
from django.urls import path
from . import views

app_name = "order"
urlpatterns = [
	path('', views.create_order, name='create_order')
]

organic_food/urls.py
from django.contrib import admin
from django.urls import path, include
from shop.views import shop as shop_view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
    path('', shop_view, name='shop')
]
if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

order/models.py
from django.db import models
from shop.models import Product

class Order(models.Model):
	first_name = models.CharField(max_length=100)
	last_name = models.CharField(max_length=100)
	email = models.EmailField()
	city = models.CharField(max_length=100)
	street = models.CharField(max_length=100)
	postal_code = models.CharField(max_length=100)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	paid = models.BooleanField(default=False)

	class Meta:
		ordering = ('-created',)

	def __str__(self):
		return 'Order: {}'.format(self.id)

	def get_total_price(self):
		return sum(product.total_price() for product in self.products.all())

class OrderProduct(models.Model):
	product = models.ForeignKey(Product, related_name='order_products', on_delete=models.CASCADE)
	order = models.ForeignKey(Order, related_name='products', on_delete=models.CASCADE)
	quantity = models.PositiveIntegerField(default=1)
	price = models.DecimalField(max_digits=10, decimal_places=2)

	def total_price(self):
		return self.quantity * self.price

shop/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
	name = models.CharField(max_length=200, db_index=True, unique=True)
	slug = models.SlugField(max_length=200, unique=True)
	
	class Meta:
		ordering = ("name", )
		verbose_name = "category"
		verbose_name_plural = "categories"

	def __str__(self):
		return self.name
	'''def get_absolute_url(self):
		return reverse('shop:catalog_by_category', args=[self.slug])'''

class Product(models.Model):
	category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name = "products")
	name = models.CharField(max_length=200, db_index=True)
	slug = models.SlugField(max_length=200, unique=True)
	description = models.TextField(blank=True)
	volume = models.PositiveSmallIntegerField()
	price = models.DecimalField(max_digits=10, decimal_places=2)
	image = models.ImageField(default="static/default.jpg", upload_to="products/%Y/%m/%d")
	available = models.BooleanField(default=False)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)

	class Meta:
		ordering=("category", )

	def __str__(self):
		return self.name

	'''def get_absolute_url(self):
		return reverse('shop:product_detail', args=[self.id])'''

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]
class CartAddProductForm(forms.Form):
	quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
	update = forms.BooleanField(required=False,	initial=False, widget=forms.HiddenInput)

order/forms.py
from django import forms
from .models import Order

class OrderForm(forms.ModelForm):
	class Meta:
		model = Order
		exclude = ['created', 'updated', 'paid']

cart/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .cart import Cart
from shop.models import Product
from .forms import CartAddProductForm

def cart_add(request, id):

	cart = Cart(request)
	product = get_object_or_404(Product, id=id)

	if request.method == 'POST':
		form = CartAddProductForm(request.POST)

		if form.is_valid():
			form_cd = form.cleaned_data
			cart.add(product, quantity=form_cd['quantity'], update_quantity=form_cd['update'])

		return HttpResponse(200)
	
	else:
		cart.add(product)
		return HttpResponse(200)

def cart_remove(request, id):

	cart = Cart(request)
	cart.remove(id)

	return HttpResponse(200)

def cart_detail(request):
	cart = Cart(request)

	for item in cart:
		item['quantity_form'] = CartAddProductForm(
			initial={'quantity':item['quantity'], 'update':True})

	return render(request, 'cart_detail.html', {'cart':cart})

order/views.py
from django.shortcuts import render
from .models import Order, OrderProduct
from .forms import OrderForm
from cart.cart import Cart
from .tasks import on_created_order

def create_order(request):
	order_form = OrderForm()
	cart = Cart(request)
	if request.method == 'POST':
		order_form = OrderForm(request.POST)
		if order_form.is_valid():
			order = order_form.save()
			for item in cart:
				OrderProduct.objects.create(
						order=order,
						product=item['product'],
						quantity=item['quantity'],
						price=item['price']
					)
			cart.clear()
			on_created_order.delay(order.id)
			return render(request, 'created_order.html', {'order':order})
	return render(request, 'create_order.html', {'order_form':order_form, 'cart':cart})
	

shop/views.py
from django.shortcuts import render
from shop.models import Product, Category

def shop(request):
	products = Product.objects.filter(available=True)
	return render(request, 'shop.html', {'products':products})

cart/templates/cart/base.html
<!DOCTYPE html>
<html>
<head>
	{% block link %}{% endblock %}
	<title>{% block title %}{% endblock %}</title>
</head>
<body>
	{% block body %}{% endblock %}
	{% block js %}{% endblock %}
</body>
</html>

cart/templates/cart_detail.html
{% extends 'cart/base.html' %}
{% load static %}

{% block link %}
	<link rel="stylesheet" href="{% static 'css/cart_style.css' %}">
{% endblock %}

{% block title %}Cart{% endblock %}

{% block body %}
	<div class="site-title">
		<a class="site-title__wrap" href="{% url 'shop' %}">
			<b class="organic">Organic</b>
			<span class="fresh-foods">fresh foods</span>
		</a>
	</div>

	<table>
		<thead>
			<tr>
				<th>Image</th>
				<th>Name</th>
				<th>Quantity</th>
				<th>Unit price</th>
				<th>Total price</th>
				<th>Remove</th>
			</tr>
		</thead>
		<tbody>
			{% for item in cart %}
				{% with product=item.product%}
					<tr id={{ product.id }}>
						<td><img src="{{product.image.url}}" alt="" width="100px"></td>
						<td><a href="{{product.get_absolute_url}}">{{product.name}}</a></td>
						<td>
							<form data-id="{{product.id}}" method="post">
								{{item.quantity_form.quantity}}
								{{item.quantity_form.update}}
								{% csrf_token %}
								<input name="submit_button" type="submit" value="Update">
							</form>
						</td>
						<td>{{product.price}}</td>
						<td>{{item.total_price}}</td>
						<td><a href="#" class="cart-remove" data-id="{{product.id}}">remove</a></td>
					</tr>
				{% endwith %}
			{% endfor %}
					<tr>
						<td>Total summ</td>
						<td colspan='4'></td>
						<td>{{cart.get_total_price}}</td>
					</tr>
					<tr>
						<td colspan="5"></td>
						<td><a href="{% url 'order:create_order' %}">Check out</a></td>
					</tr>
		</tbody>
	</table>
{% endblock %}

{% block js %}
	<script type="text/javascript" src="{% static 'js/cart.js' %}"></script>>
{% endblock %}

order/templates/create_order.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Order</title>
</head>
<body>
	<table>
		<thead>
			<tr>
				<th>Product name</th>
				<th>Product quantity</th>
				<th>Cost</th>
			</tr>
		</thead>
		<tbody>
			{% for item in cart %}
				<tr>
					<td>{{item.product.name}} x</td>
					<td>{{item.quantity}}</td>
					<td>{{item.total_price}}</td>
				</tr>
			{% endfor %}
				<tr>
					<td>Total price: {{cart.get_total_price}}</td>
				</tr>
		</tbody>
	</table>

	<form action="{% url 'order:create_order' %}" method="post">
		{{order_form.as_p}}
		{% csrf_token %}
		<input type="submit" value="Get order">
	</form>
</body>
</html>

order/templates/created_order.html
<h1>Thanks you!</h1>

<p>Your order was sucefully created! Number of your order is: {{order.id}}</p>
<a href="{% url 'shop' %}">Back</a>